kyperbelt/adapted-strength

README.md
[Jira](https://terabite-adapted-strength.atlassian.net/browse/ADAPTEDS-41)
Made an addition of my discord handle to the project readme.
=> docs: Added Discord for Jonathan Camarena to README.

README.md
docs: eddited readme
Concise description of what task/feature/bug this pull request is addressing.
=> Init commit

README.md
Adding in my Discord name to the README.md document
Added in "Discord: Lumikha :
Nuffin'
=> Casey cubed

README.md
Modified the file "README.md" to include my Discord username.
=> docs: Added Discord for Danny Zhou to README.

README.md
Added Discord contact info
Modified Readme.md
=> Added Discord for Jeff H

README.md
Concise description of what task/feature/bug this pull request is addressing.
=> Added Ahmed's Discord

README.md
Concise description of what task/feature/bug this pull request is addressing.
=> Updated readme to include my discord username

README.md
Concise description of what task/feature/bug this pull request is addressing.
=> Added Discord for David Castrejon

README.md
I added my discord to the readme file. I apologize; I was rewatching the git video and realized I never added my discord to the file.
=> Description: Added Amir Talakoob's Discord to the readme file

frontend/adapted_strength-app/package-lock.json, frontend/adapted_strength-app/package.json, frontend/adapted_strength-app/src/App.js, frontend/adapted_strength-app/src/pages/ForgotPassword.jsx, frontend/adapted_strength-app/src/pages/Home.jsx, frontend/adapted_strength-app/src/pages/Layout.jsx, frontend/adapted_strength-app/src/pages/NotFound.jsx
We did not have a way to do basic routing, so we were basically all working on the same file. This was not ideal. Added routing through ReactRouter module and now we can hit different routes to get different pages, and each page gets its own JSX file in the pages folder. 
:warning: Make sure to run `npm install` so that it installs react-router locally before you do `npm start`. 
Does the project build? yes, it builds and the routes work correctly.
=> Add react router

docs/coding_standards.md
Codifies team coding standards, to hopefully establish shared standards and explicitly define assumptions.
=> Codify Coding Standards

frontend/adapted_strength-app/src/App.js, frontend/adapted_strength-app/src/components/navBar.jsx, frontend/adapted_strength-app/src/pages/SignUp.jsx, frontend/adapted_strength-app/src/pages/SignUpAdditional.jsx
Added pages SignUp and SignUpAdditional, the first one gets email and password, and the second one handles other personal information.
Access restriction is not possible to be defined as of now.
Created two JSX files, handling two forms that are designed to (after being connected to the backend) send a JSON containing new user information.
Most of the input validations are done, but \Confirmed password needs to be worked on.
Program runs, as well as the regex for the password and other required fields.
The page is connected to the home page, and the buttons function correctly.
=> Story: ADAPTEDS-13, Task: ADAPTEDS-49

.vscode/settings.json, authorization/.vscode/settings.json, authorization/src/main/java/com/terabite/authorization/AuthorizationApplication.java, authorization/src/main/java/com/terabite/authorization/controller/AuthorizationController.java, authorization/src/main/java/com/terabite/authorization/service/UserInformation.java, authorization/src/main/resources/application.properties
Endpoint changes - now implicitly invoking Jackson behind the senses for serialization /  deserialization of POJPO DTO.
Yes
Manual testing of endpoint
=> Quick changes

frontend/adapted_strength-app/package-lock.json, frontend/adapted_strength-app/package.json, frontend/adapted_strength-app/src/pages/Login.jsx
Created foundation for ADAPTEDS-48: Login page creation
The login page does work as intended, with the base features implemented. The buttons lead to the home page, and the routes lead to where they should.
No testing required in PR.
=> ADAPTEDS-48 Functioning Login page created

frontend/adapted_strength-app/src/App.js, frontend/adapted_strength-app/src/pages/Memberships.jsx
Jira task 92 - Amit Talakoob
Membership page for the adapted strength that shows the different plans and their pricings.
The jsx file is ready and complete, also it is accessible through /memberships
The project builds and on-hover works. Page is accessible and matches the current data.
=> Memberships page - jira task 92

frontend/adapted_strength-app/src/App.js, frontend/adapted_strength-app/src/pages/HealthQuestionnaire.jsx, frontend/adapted_strength-app/src/pages/SignUp.jsx, frontend/adapted_strength-app/src/pages/SignUpAdditional.jsx, frontend/adapted_strength-app/src/pages/TermsOfService.jsx, package-lock.json
Created a terms of service and health questionnaire.
=> [ADAPTEDS-43] Pushing terms of service and questionnaire

frontend/adapted_strength-app/package-lock.json, frontend/adapted_strength-app/package.json, frontend/adapted_strength-app/src/App.js, frontend/adapted_strength-app/src/api/VideoApi.js, frontend/adapted_strength-app/src/pages/VideoLibrary.jsx
[ADAPTEDS-98] Movement library where the coach can add, delete, and modify the videos, and the members can watch them.
A frontend page was designed and created, add and delete functionalities are completed and tested using frontend test objects. Edit functionalities still need to be developed. 
Yes, the project builds. Add and delete functionalities are tested using frontend test objects, but more tests are needed after the backend is connected.
Adding and removing videos through the UI.
=> [ADAPTEDS 98] Video (Movement) Library frontend 

frontend/adapted_strength-app/src/components/navBar.jsx, frontend/adapted_strength-app/src/pages/Login.jsx
Created hamburger menu
Improved navbar implementation in navBar.jsx menu. Navigation menu is now a hamburger style menu located on top right of screen (locked), and will toggle a menu that slides from the right.
All links are functional as before, and any links previously on the navbar have been migrated over to the new menu type.
=> Adptds-XX: Pre-Sprint 07 fix

frontend/adapted_strength-app/src/pages/Chat.jsx
Chat video implementation in the chat box.
Added a button that browse for local files and uses it to upload onto the chat. Needs to press "Send" for the video to actually upload. The order goes that the video will be uploaded first before the chat message. Overall, reworked some of the logic associated with the subscription feature.
Functional testing by using local videos and sending messages.
=> [ADAPTEDS-67 Frontend Chat Video integration

authorization/src/main/java/com/terabite/authorization/controller/AuthorizationController.java, frontend/adapted_strength-app/src/api/AuthApi.js
Quick and dirty endpoint to check if the authenticated user has a given ROLE using the AuthApi.hasRole(role) function.
=> Authorization check fix

frontend/adapted_strength-app/src/pages/Chat.jsx
Now shows file name when file input it selected.
Added div above the flex container.
Functional Testing
=> [ADAPTEDS-136] Frontend Video Chat Touchup

frontend/adapted_strength-app/src/api/ApiUtils.js, frontend/adapted_strength-app/src/components/navBar.jsx, frontend/adapted_strength-app/src/pages/Login.jsx
Mini fix
Left some sensitive information on the branch. Fixing this now
NO JIRA, no testing needed
=> Quickfix (NO_JIRA)

actions/deploy.yaml
=> Inital CICD

authorization/src/main/java/com/terabite/authorization/config/SecurityConfig.java, authorization/src/main/java/com/terabite/chat/controller/ChatController.java, authorization/src/main/java/com/terabite/leaderboard/controller/LeaderboardController.java, authorization/src/main/java/com/terabite/movement/controller/CategoryController.java, authorization/src/main/java/com/terabite/movement/controller/MovementController.java, authorization/src/main/java/com/terabite/payment/controller/PaymentController.java, authorization/src/main/java/com/terabite/payment/controller/WebhookController.java, authorization/src/main/java/com/terabite/programming/controller/ProgrammingControler.java, authorization/src/main/java/com/terabite/programming/controller/RepCycleNoteController.java, authorization/src/main/java/com/terabite/video/controller/VideoController.java
End point authorizations was set in this commit for all the endpoints.
Yes, the project was built. A short testing will be done after ADAPTEDS-135
=> ADAPTEDS-114, added preauthorization to endpoints
